name: Publish to npmjs.com

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          registry-url: 'https://registry.npmjs.org/'
      - run: bun install
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: bun test
      - run: bun run build
      - run: bun add -g npm
      - run: npm shrinkwrap
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
